### PR TITLE
[Reviewer: Jim] Improve compression performance

### PR DESCRIPTION
**Pull request by mirw**
Andy,

Please can you review my fix to improve compression performance.  In my testing, this improves performance by about 20% while worsening compression by about 1%.

Please don't merge until I've got the SAS team to review.

Thanks,

Matt

### CODE REVIEW

**Comment by bossmc** [comment]
Code looks good, comments look good, overall 9/10, gold star.

**Comment by mirw** [comment]
Jim,

Please can you review my fix to improve compression performance. In my testing, this improves performance by about 20% while worsening compression by about 1%.

Thanks,

Matt

**Comment by jw2** [comment]
Helpdesk – please review.

**Comment by benritchie** [comment]
What's the impact of this on SAS decode performance?  
I assume this will mean the SAS DB size will go up by about 1%.  Do you have sufficient headroom in your Clearwater SAS sizings to absorb that?

**Comment by mirw** [comment]
Thanks for your comments, and sorry for the delay in responding!

Even with this fix, the performance degradation caused by SAS compression on Clearwater is too large, so we're stepping back and considering alternatives.  As a result I'm going to close this pull request unmerged.

**Pull request closed without merging**
